### PR TITLE
Layers

### PR DESCRIPTION
**Pull request by jmy-kellogg**
added layers component

### CODE REVIEW

**Comment by DougVonMoser** [comment]
bitmoji

**Comment by jmy-kellogg** [comment]
this is in ref to #17  @wjrhee please advise if this will be able to be merged with your form updates or if it should be close when you get a chance. thanks

**Comment by wjrhee** [comment]
added inline editing, storing selected selected node, adding new layers, storing layers, adding nodes, storing nodes on the correct layers.

**Comment by wjrhee** [comment]
@dejongnj @DougVonMoser @jmy-kellogg please review and merge

**Pull request merged**
