### PR TITLE
Bus design

### PR DESCRIPTION
**Pull request by dejongnj**
I wired up and styled some things on the business settings pages. I am about to add the ability to update the head node question.

### CODE REVIEW

**Comment by dejongnj** [comment]
I added the ability to change headNode question. I'll be moving onto minor functionality of displaying whether the start button is added or not.

**Comment by dejongnj** [comment]
I have fixed the get started button so that it displays correctly

**Comment by dejongnj** [comment]
I update the business info page to also display tooltips. I will move onto the persistent menu settings next and make it look a little more presentable

**Comment by wjrhee** [comment]
nick this looks awesome.  you're a monster

**Pull request merged**
