### PR TITLE
Design

### PR DESCRIPTION
**Pull request by jmy-kellogg**
updated some css stuff

### CODE REVIEW

**Comment by DougVonMoser** [comment]
bitmoji

**Comment by wjrhee** [comment]
@jmy-kellogg why was the answer input removed from the single form?

**Comment by jmy-kellogg** [comment]
Updated some color but still tweaking. Scrolling is working for the most part on Make bot phase. Still having trouble getting the top right question div to stick. Open to suggestions

**Comment by jmy-kellogg** [comment]
@wjrhee the add button automatically adds an empty line that can be edited. I removed a lot of clutter let me know if it doesn't work

**Pull request merged**
